name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add msbuild to PATH
        if: matrix.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.2
        env:
          # configure cibuildwheel to build native archs ('auto'), and some
          # emulated ones
          # CIBW_ARCHS_LINUX: ${{ matrix.arch }}

          CIBW_BUILD_FRONTEND: "build"
        # CIBW_ARCHS_MACOS: x86_64 universal2 arm64
        # CIBW_ARCHS_LINUX: aarch64
        # CIBW_BEFORE_BUILD: yum -y install fftw-devel
          CIBW_SKIP: pp*
          # CIBW_BUILD: "*-manylinux_x86_64 *-manylinux_i686 *-manylinux_aarch64"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
